import Head from "next/head";

// components
import Header from "@/components/Header";
import Hero from "@/components/Hero";
import About from "@/components/About";
import Articles from "@/components/Articles";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Food Truck</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Hero />
        <About />
        <Articles />
        <Footer />
      </main>
    </>
  );
}
